### ISSUE TITLE
ExtractComponentFrom3DTensor vs TensorToVectorComponent

### ISSUE THREAD

**Issue by cecs1** [cookpa/antsDTOrientationTests#1]
Hello,

Apologies, if this is a basic question but can someone please tell me the difference between these two commands in ANTS.
Assuming I have a diffusion tensor, dt (say)

ImageMath 3 dxx.nii.gz ExtractComponentFrom3DTensor dt.nii.gz xx

vs

ImageMath 3 dxx.nii.gz TensorToVectorComponent dt.nii.gz 3

As far as I can tell, these should give the same result ie the xx component of the tensor, but when I apply them they give somewhat different results. The ExtractComponentFrom3DTensor gives only a positive result (0 to 10.9 (say)), whilst the TensorToVectorComponent  gives a range from negative to positive (-1.7 to 10.9 (say)). 

Which one should be used to extracted the xx component of the tensor?

Many thanks,
Chris

**Comment by cookpa** [comment]
I prefer the first way, but both produce the same result for me. Do you have example data where they are different?

**Comment by cecs1** [comment]
​Many thanks Philip.

I've attached the DTI tensor at the following link (It has been warped and reoriented into MNI space)

ANTS 2.2 is used for all registrations



https://drive.google.com/file/d/1ryakB5piJlJ0TDt5ia7frTJonp0AKizA/view?usp=share_link



ImageMath 3 dxx.nii.gz ExtractComponentFrom3DTensor new-dtReoriented.nii.gz xx



ImageMath 3 other-dxx.nii.gz TensorToVectorComponent new-dtReoriented.nii.gz 3



#############################

fslstats dxx.nii.gz -R

-2.136708 9.79766


fslstats dxx.nii.gz -M

0.689377


Compared to:


fslstats other-dxx.nii.gz -R

0.000000 9.797660


fslstats other-dxx.nii.gz -M

1.363560


############################


Any advice would be appreciated as both can't be correct.

Thanks,
Chris



---------------------------------------------

Dr Chris Steward,

Dept of Radiology,

University of Melbourne,

Royal Melbourne Hospital

E: ***@***.******@***.***>

Ph: +613 90356508

---------------------------------------------


________________________________
From: Philip Cook ***@***.***>
Sent: 12 November 2022 08:30
To: cookpa/antsDTOrientationTests ***@***.***>
Cc: Chris Steward ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [cookpa/antsDTOrientationTests] ExtractComponentFrom3DTensor vs TensorToVectorComponent (Issue #1)


External email: Please exercise caution

________________________________
I prefer the first way, but both produce the same result for me. Do you have example data where they are different?

**Comment by cookpa** [comment]
I think I found the bug, fixed in 2021

https://github.com/ANTsX/ANTs/pull/1139

I confirmed this is fixed in the latest release:

```
ImageMath 3 dxxComponent.nii.gz ExtractComponentFrom3DTensor new-dtReoriented.nii.gz xx
ImageMath 3 dxxComponentVec.nii.gz TensorToVectorComponent new-dtReoriented.nii.gz 3
ImageMath 3 diff.nii.gz - dxxComponent.nii.gz dxxComponentVec.nii.gz
MeasureMinMaxMean 3 diff.nii.gz 
```

reports

```
diff.nii.gz Max : [0] Min : [0] Mean : [0] Var : 0 SD : 0
```

**Comment by cookpa** [comment]
Actually, I think that was a different bug, affecting ExtractComponentFrom3DTensor. The error in `TensorToVectorComponent` dates back even further, but was [fixed here](https://github.com/ANTsX/ANTs/commit/aa529839865c104bb9b579998eb7b392454bb518)

**Comment by cecs1** [comment]
Many thanks Philip! I should've kept my version up-to-date!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Philip Cook ***@***.***>
Sent: Tuesday, November 15, 2022 8:38:39 AM
To: cookpa/antsDTOrientationTests ***@***.***>
Cc: Chris Steward ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [cookpa/antsDTOrientationTests] ExtractComponentFrom3DTensor vs TensorToVectorComponent (Issue #1)


External email: Please exercise caution

________________________________
Actually, I think that was a different bug, affecting ExtractComponentFrom3DTensor. The error in TensorToVectorComponent dates back even further, but was fixed here<https://github.com/ANTsX/ANTs/commit/aa529839865c104bb9b579998eb7b392454bb518>
